spring:
  profiles:
    active: dev

---
spring:
  application:
    name: springcloud-eureka

server:
  port: 8001

eureka:
  instance:
    hostname: eureka8001.com     # eureka服务端的实力名称
  client:
    fetch-registry: false  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false   # false表示自己不需要向注册中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)

---
spring:
  application:
    name: sringcloud-config

server:
  port: 8011

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka8001.com:8001/eureka/
