spring:
  profiles:
    active: dev

---
spring:
  application:
    name: sringcloud-config

server:
  port: 8011

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka8001.com:8001/eureka/
